version: '3'

services:
  postgres:
    container_name: c_postgres
    build:
      context: .
      dockerfile: ./model/Dockerfile
    image: i_postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: on-failure

  redis:
    container_name: c_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: on-failure

  django:
    container_name: c_django
    build:
      context: ./django
      dockerfile: Dockerfile
    image: i_django
    volumes:
      - ./django:/bk_django
      - ./django/static:/bk_django/staticfiles
      - ./media:/bk_django/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    command: ["./waitPostgres.sh", "postgres", "uvicorn", "web.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
    restart: on-failure

  nginx:
    container_name: c_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: i_nginx
    volumes:
      - ssl_certificates:/etc/ssl
      - ./django/static:/bk_django/staticfiles
      - ./media:/bk_django/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    restart: on-failure

volumes:
  static_volume:
  django_volume:
  ssl_certificates:
    driver: local
    name: ssl_certificates
    driver_opts:
      type: none
      o: bind
      device: ./ssl
